source 'https://rubygems.org'

gem 'rails', '~> 7.1.5'
gem 'sqlite3', '~> 1.7'
gem 'puma', '~> 6.4'
gem 'rack-cors'
gem 'httparty'

# Boot performance
gem 'bootsnap', require: false

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
end
